egovernments/works-mdms-data

- data/pb/works/BeneficiaryType.json
- data/pb/works/EntrustmentMode.json
- data/pb/works/NatureOfWork.json
- data/pb/works/TypeOfWork.json
Please review this MDMS files.
> Works MDMS data

- data/pb/common-masters/WageSeekerSubSkills.json
This PR has changes for new config for Sub Skills. This is as part of CR PFM - 2068.
> Created config for sub skills

- data/pb/commonUiConfig/CreateProjectConfig.json
- data/pb/works/DocumentConfig.json
This Pr includes:
- basic config for rendering Create Project screen 
Does not include:
- custom functions such as useTranslation(), etc
> PFM-2390 Added CreateProjectConfig.json

- data/pg/works/TargetDemography.json
In TargetDemography.json, the "effectiveFrom" attribute aims to fetch the current date and thus I have given a placeholder as "getCurrentDate" for a function which needs to be handled in the UI.
> Added TargetDemography.json

- data/pg/commonMuktaUiConfig/CreateEstimateConfig.json
- data/pg/commonMuktaUiConfig/CreateProjectConfig.json
- data/pg/commonMuktaUiConfig/InboxMusterConfig.json
- data/pg/commonMuktaUiConfig/InboxProjectConfig.json
- data/pg/commonMuktaUiConfig/SearchEstimateConfig.json
- data/pg/commonMuktaUiConfig/SearchProjectConfig.json
- data/pg/commonUiConfig/InboxMusterConfig.json
- data/pg/commonUiConfig/InboxProjectConfig.json
- data/pg/commonUiConfig/SearchEstimateConfig.json
* Rename searchEstimateConfig.json to SearchEstimateConfig.json
* Update and rename musterInboxConfig.json to InboxMusterConfig.json
* Update and rename projectInboxConfig.json to InboxProjectConfig.json
* PFM-2538  :: Added all the ui configs to the Mukta config folder
> PFM-2538 :: formatted the file names  (#65)

- data/pg/works/DocumentConfig.json
Removed 'isMultiple' flag since it is not required (maxFilesAllowed can be used) Added 'showTextInput' flag to show text input to add file name
> Added 'showTextInput' flag in Document Config

- data/pg/works/ContractType.json
Please review it and take appropriate action.
> Contract service | MDMS data updated with introduction of one more field

- data/pg/ACCESSCONTROL-ROLEACTIONS/roleactions.json
> Updated Estimate action ID

- data/pg/ACCESSCONTROL-ACTIONS-TEST/actions-test.json
Add role action mapping for /wms/project/_search
> Add new role action

- data/pg/ACCESSCONTROL-ROLEACTIONS/roleactions.json
Corresponding changes in role actions mdms
> QA: Update role-actions

- data/pg/commonMuktaUiConfig/CreateProjectConfig.json
> QA: Update Project Config

- data/pg/commonMuktaUiConfig/SearchProjectConfig.json
> QA: PFM-2393 Update config

- data/pg/works/DocumentConfig.json
QA: PFM-2396 Update Document Configs
> QA: PFM-2396 Update Configs

- data/pg/commonMuktaUiConfig/SearchEstimateConfig.json
> PFM-2474-- Changes in QA

- data/pg/commonMuktaUiConfig/CreateEstimateConfig.json
> PFM-2471- changes

- data/pg/inbox-v2/SearchConfiguration.json
- data/pg/works/ContractType.json
> Pfm 2526 updates

- data/pg/commonMuktaUiConfig/EstimateInboxConfig.json
> PFM-2472-- Changes

- data/pg/ACCESSCONTROL-ROLES/roles.json
Updated with Mukta user role action
> Updated with Mukta user role action

- data/pg/ACCESSCONTROL-ROLEACTIONS/roleactions.json
> Updating mukta user role

- data/pg/inbox-v2/InboxConfiguration.json
> Updated the mukta requirement

- data/pg/ACCESSCONTROL-ACTIONS-TEST/actions-test.json
- data/pg/ACCESSCONTROL-ROLEACTIONS/roleactions.json
- data/pg/works/ContractType.json
> Pfm 2526 fuzzy

- data/pg/commonMuktaUiConfig/EstimateInboxConfig.json
Updated the business service name to match with QA yaml
> Updated the business service name to match with QA yaml

- data/pg/commonMuktaUiConfig/SearchProjectConfig.json
Updated the role and its actions on project screens
> Updated the role and its actions on project screens

- data/pg/ACCESSCONTROL-ROLEACTIONS/roleactions.json
Update roleactions for updated User roles
> Update roleactions for updated User roles

- data/pg/ACCESSCONTROL-ROLEACTIONS/roleactions.json
This reverts commit f9a884cced0e2f469aad9c6e85d921ebe741fe49.
> Revert "Updated the role action for WO verifier (#178)"

- data/pg/ACCESSCONTROL-ROLEACTIONS/roleactions.json
- data/pg/ACCESSCONTROL-ROLES/roles.json
Reverts egovernments/works-mdms-data#179
> Revert "Updated the WO action role"

- data/pg/common-masters/StateInfo.json
> PFM-2579 :: added mukta logo for shg app (#197)

- data/pg/common-masters/StateInfo.json
> Added mukta logo for SHG

- data/pg/inbox-v2/SearchConfiguration.json
- data/pg/works/ContractType.json
> Pfm 2526 fuzzy update

- data/pg/inbox-v2/SearchConfiguration.json
- data/pg/works/ContractType.json
> PFM-2624 | Estimate service | search on ward and project name

- data/pg/inbox-v2/SearchConfiguration.json
- data/pg/works/ContractType.json
> Pfm 2624 estimate fuzzy

- data/pg/ACCESSCONTROL-ACTIONS-TEST/actions-test.json
- data/pg/ACCESSCONTROL-ROLEACTIONS/roleactions.json
- data/pg/inbox-v2/SearchConfiguration.json
- Add Fuzzy search on organisation name
- Add other search parameters
- Add Role Action mapping for organisation fuzzy search
> Add fuzzy search for Org Service

- data/pg/DataSecurity/DecryptionABAC.json
> PFM-2469 :: Created DecryptionABAC.json (#336)

- data/pg/ACCESSCONTROL-ACTIONS-TEST/actions-test.json
- data/pg/ACCESSCONTROL-ROLEACTIONS/roleactions.json
- data/pg/works/ExpenseHeads.json
Added roles and role action mappings for calculator
> Changes for calculator service

- data/pg/common-masters/IdFormat.json
Removed estimate detailed sequence number
> Removed estimate detailed sequence number

- data/pg/commonMuktaUiConfig/InboxMusterConfig.json
- data/pg/commonMuktaUiConfig/SearchOrganisationConfig.json
PFM-2715 - 
1. Removed Amount Column from Muster Inbox
> PFM-2715 - Removed Amount Column from Muster Inbox

- data/pg/works/ExpenseHeads.json
> Update Module name

- data/statea/ACCESSCONTROL-ROLEACTIONS/roleactions.json
> Added role action mapping for project and contract

- data/pg/expense/ApplicableCharges.json
- data/pg/expense/HeadCodes.json
Added GST charge for purchase bill as an expense.
> Added GST to applicable charges

- data/pg/ACCESSCONTROL-ACTIONS-TEST/actions-test.json
- data/pg/ACCESSCONTROL-ROLEACTIONS/roleactions.json
* Update actions-test.json
* Update roleactions.json
> Added Role action mapping for the Bill generate option  (#2)

- data/pg/commonMuktaUiConfig/CreatePurchaseBillConfig.json
This PR has changes for - 
1. Configs for Create Purchase Bills.
> Updated config for create purchase bill

- data/pg/works/DocumentConfig.json
Reverts egovernments/works-mdms-data#495
> Revert "Update Work Order configs for PFM-2764"

- data/statea/works/DocumentConfig.json
Reverts egovernments/works-mdms-data#496
> Revert "Update Work Order configs as per PFM-2764"

- data/pg/commonUiConfig/CreateProjectConfig.json
Updated the Project Description validation regex in order to allow ,(comma) as well
> PFM-3034 : Updated Project Create Config

- data/pg/commonMuktaUiConfig/CreateProjectConfig.json
updated the regex expression for validation which includes ,(comma) as well.
> PFM-3034 : updated Create Project Config

- data/pg/commonMuktaUiConfig/CreateOrganizationConfig.json
updated the type of the field from number to text in order to accept masked value as well in the input while modifying.
> PFM-3033 : updated Create Organisation Config

- data/pg/commonUiConfig/CBOMusterInboxConfig.json
- data/pg/commonUiConfig/CBOMyWorks.json
> CBO Inbox pages Status config added

- data/statea/commonMuktaUiConfig/EstimateInboxConfig.json
- data/statea/commonMuktaUiConfig/InboxConfigContracts.json
- data/statea/commonMuktaUiConfig/SearchContractConfig.json
- data/statea/commonMuktaUiConfig/SearchEstimateConfig.json
- data/statea/commonMuktaUiConfig/SearchEstimateWMSConfig.json
> PFM-3047 :: Removed the locality in all inbox to have uniformity

- data/pg/commonMuktaUiConfig/EstimateInboxConfig.json
Removed the Project Viewer role for Create Estimate link in inbox
> PFM-3039 : Update EstimateInboxConfig.json

- data/pg/inbox-v2/InboxConfiguration.json
- data/pg/inbox-v2/SearchConfiguration.json
> Add wms expense

- data/pg/ACCESSCONTROL-ACTIONS-TEST/actions-test.json
- data/pg/ACCESSCONTROL-ROLEACTIONS/roleactions.json
- data/pg/ACCESSCONTROL-ROLES/roles.json
> PFM-2920 | Add dashboard role and actions

- data/pg/dss-dashboard/dashboard-config.json
> PFM-2920 | Add dashboard config

- data/pg/dss-dashboard/dashboard-config.json
> Change tenantId in Dashboard Config

- data/pg/inbox-v2/SearchConfiguration.json
Updated the search order by created time and list in descending order.
> Updated the search order by created time

- data/pg/inbox-v2/SearchConfiguration.json
> PFM-3473:: Search by id for individuals to fetch the attendees Individual details

- data/pg/ACCESSCONTROL-ACTIONS-TEST/actions-test.json
- data/pg/ACCESSCONTROL-ROLEACTIONS/roleactions.json
> Add getChartV2 to role actions
